

CREATE TABLE public.dance_doodle_game (
    id bigint NOT NULL,
    age integer NOT NULL,
    child_id character varying(255) NOT NULL,
    cool_arms integer,
    crossy_play integer,
    date_time timestamp(6) without time zone NOT NULL,
    isasd boolean,
    is_training_allowed boolean NOT NULL,
    open_wings integer,
    session_id character varying(255) NOT NULL,
    shh_fun integer,
    silly_boxer integer,
    suspectedasd boolean NOT NULL,
    videourl character varying(255),
    happy_stand integer,
    stretch integer,
    school_task_id character varying(255)
);


CREATE TABLE public.gaze_game (
    id bigint NOT NULL,
    age integer NOT NULL,
    child_id character varying(255) NOT NULL,
    date_time timestamp(6) without time zone NOT NULL,
    isasd boolean,
    is_training_allowed boolean NOT NULL,
    round1count integer,
    round2count integer,
    round3count integer,
    session_id character varying(255) NOT NULL,
    suspectedasd boolean NOT NULL,
    school_task_id character varying(255)
);

CREATE TABLE public.gesture_game (
    id bigint NOT NULL,
    age integer NOT NULL,
    butterfly integer,
    child_id character varying(255) NOT NULL,
    closed_fist integer,
    date_time timestamp(6) without time zone NOT NULL,
    dua integer,
    heart integer,
    isasd boolean,
    is_training_allowed boolean NOT NULL,
    open_palm integer,
    pointing_up integer,
    session_id character varying(255) NOT NULL,
    spectacle integer,
    suspectedasd boolean NOT NULL,
    thumbs_down integer,
    thumbs_up integer,
    victory integer,
    videourl character varying(255),
    iloveyou integer,
    type character varying(255) DEFAULT 'practice'::character varying,
    school_task_id character varying(255)
);


CREATE TABLE public.mirror_posture_game (
    id bigint NOT NULL,
    age integer NOT NULL,
    child_id character varying(255) NOT NULL,
    date_time timestamp(6) without time zone NOT NULL,
    isasd boolean,
    is_training_allowed boolean NOT NULL,
    kiss integer,
    mouth_open integer,
    session_id character varying(255) NOT NULL,
    showing_teeth integer,
    suspectedasd boolean NOT NULL,
    videourl character varying(255),
    looking_sideways integer,
    school_task_id character varying(255)
);


CREATE TABLE public.repeat_with_me_game (
    id bigint NOT NULL,
    age integer NOT NULL,
    average_score double precision,
    child_id character varying(255) NOT NULL,
    completed_rounds integer,
    date_time timestamp(6) without time zone NOT NULL,
    isasd boolean,
    is_training_allowed boolean NOT NULL,
    round10score double precision,
    round10target_text character varying(1000),
    round10transcribed_text character varying(1000),
    round11score double precision,
    round11target_text character varying(1000),
    round11transcribed_text character varying(1000),
    round12score double precision,
    round12target_text character varying(1000),
    round12transcribed_text character varying(1000),
    round1score double precision,
    round1target_text character varying(1000),
    round1transcribed_text character varying(1000),
    round2score double precision,
    round2target_text character varying(1000),
    round2transcribed_text character varying(1000),
    round3score double precision,
    round3target_text character varying(1000),
    round3transcribed_text character varying(1000),
    round4score double precision,
    round4target_text character varying(1000),
    round4transcribed_text character varying(1000),
    round5score double precision,
    round5target_text character varying(1000),
    round5transcribed_text character varying(1000),
    round6score double precision,
    round6target_text character varying(1000),
    round6transcribed_text character varying(1000),
    round7score double precision,
    round7target_text character varying(1000),
    round7transcribed_text character varying(1000),
    round8score double precision,
    round8target_text character varying(1000),
    round8transcribed_text character varying(1000),
    round9score double precision,
    round9target_text character varying(1000),
    round9transcribed_text character varying(1000),
    session_id character varying(255) NOT NULL,
    suspectedasd boolean NOT NULL,
    school_task_id character varying(255)
);
