spring:
  datasource:
    url: jdbc:postgresql://ep-lively-bar-a13qc84j-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_qI5h7gaVBkKM
    driver-class-name: org.postgresql.Driver

  # datasource:
  #   url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
  #   username: postgres.xvnkidedwtkewyyzsbka
  #   password: pscjscsschsc
  #   driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1071741181540-qseioooi5rqsu488e1ac3c8um9ee2jbp.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

  # Email configuration - Using SendGrid for real verification
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey # This is always 'apikey' for SendGrid
    password: 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 # Use environment variable
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 10000
          connectiontimeout: 10000
          writetimeout: 10000

# Logging for debugging
logging:
  level:
    org.springframework.mail: DEBUG
    com.example.jwt_auth: DEBUG

jwt:
  secret: 8cf840b09b43b5fc6a7d3cfb8311200b67ff362f449e7b3cbde066e56abccd10a99981544fb73910833668fe470b22f6e7e30d2acb66d84e82bc960ac404c63d

server:
  port: 8080
