server:
  port: 8085

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Authentication Service (JWT Auth)
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0

        # OAuth2 Authorization Service
        - id: oauth2-service
          uri: http://localhost:8080
          predicates:
            - Path=/oauth2/**
          filters:
            - StripPrefix=0

        # Parent Service
        - id: parent-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/parents/**
          filters:
            - StripPrefix=0

        # Parent Service - Tickets
        - id: parent-tickets-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/tickets/**
          filters:
            - StripPrefix=0

        # Parent Service - Test
        - id: parent-test-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/test/**
          filters:
            - StripPrefix=0

        # Doctor Service
        - id: doctor-service
          uri: http://localhost:8093
          predicates:
            - Path=/api/doctor/**
          filters:
            - StripPrefix=0

        # School Service
        - id: school-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/school/**
          filters:
            - StripPrefix=0

        # Admin Service
        - id: admin-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=0

        # Game Services
        - id: dance-doodle-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/games/dance-doodle/**
          filters:
            - StripPrefix=2

        - id: gaze-game-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/games/gaze/**
          filters:
            - StripPrefix=2

        - id: gesture-game-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/games/gesture/**
          filters:
            - StripPrefix=2

        - id: mirror-posture-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/games/mirror-posture/**
          filters:
            - StripPrefix=2

        - id: repeat-with-me-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/games/repeat-with-me/**
          filters:
            - StripPrefix=2

        # AI Chat Service
        - id: nuru-chat-service
          uri: http://localhost:8094
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=0

        # AI Agent Service (Python)
        - id: nuru-agent-service
          uri: http://localhost:8000
          predicates:
            - Path=/api/ai/**
          filters:
            - StripPrefix=1

        # Game Model Server (Python)
        - id: game-model-server
          uri: http://localhost:8097
          predicates:
            - Path=/api/models/**
          filters:
            - StripPrefix=1

      # Global CORS configuration
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://localhost:5173"
              - "https://neronurture.app"
              - "http://127.0.0.1:3000"
              - "http://127.0.0.1:3001"
              - "http://127.0.0.1:5173"
              - "http://127.0.0.1:8081"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

# JWT Configuration
jwt:
  secret: 8cf840b09b43b5fc6a7d3cfb8311200b67ff362f449e7b3cbde066e56abccd10a99981544fb73910833668fe470b22f6e7e30d2acb66d84e82bc960ac404c63d

# Logging
logging:
  level:
    org.springframework.cloud.gateway: INFO
    com.example.gateway: DEBUG
