spring:
  datasource:
    url: jdbc:postgresql://ep-lively-bar-a13qc84j-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
    username: neondb_owner
    password: npg_qI5h7gaVBkKM
    driver-class-name: org.postgresql.Driver

  # datasource:
  #   url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres
  #   username: postgres.xvnkidedwtkewyyzsbka
  #   password: pscjscsschsc
  #   driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8083
